### ISSUE TITLE
accessing SPQR_qmult from C

### ISSUE THREAD

**Issue by lkapelevich** [jluttine/suitesparse#10]
In https://github.com/jluttine/suitesparse/blob/master/SPQR/Source/SuiteSparseQR_qmult.cpp there are functions to apply a Q factor to a dense or sparse matrix. But in this header file: https://github.com/jluttine/suitesparse/blob/003319cab6429a61aed5b311f5957fce28ce06fd/SPQR/Include/SuiteSparseQR_C.h#L196 the description says `SuiteSparseQR_C_qmult` applies only for the dense case. Is there is no C interface for applying Q to a sparse matrix? Or am I missing something?

**Comment by ecsx1** [comment]
This is not the official SuiteSparse repo. It's just a copy.
Please submit your issue to the official repo maintained by the author (Tim Davis): https://github.com/DrTimothyAldenDavis/SuiteSparse

Reference https://github.com/jluttine/suitesparse/issues/11

**Comment by lkapelevich** [comment]
Glad to see the official repo on Github :-)
