### ISSUE TITLE
cannot find -lmetis during 'sudo make install INSTALL=/usr/local'

### ISSUE THREAD

**Issue by gunshi** [jluttine/suitesparse#3]
I am trying to compile SuiteSparse on Ubuntu 14.04.
I ran make in the suitesparse directory and i ran without erros.
In the bin folder I have the following executables:

/home/gunshi/Downloads/SuiteSparse/bin/cmpfillin
/home/gunshi/Downloads/SuiteSparse/bin/gpmetis
/home/gunshi/Downloads/SuiteSparse/bin/graphchk
/home/gunshi/Downloads/SuiteSparse/bin/m2gmetis
/home/gunshi/Downloads/SuiteSparse/bin/mpmetis
/home/gunshi/Downloads/SuiteSparse/bin/ndmetis

I can also see libmetis.so inside /home/gunshi/Downloads/SuiteSparse/metis-5.1.0/build/Linux-x86_64/libmetis

On trying to do :
sudo make install INSTALL=/usr/local

I get:

( cd SuiteSparse_config && make install )
make[1]: Entering directory `/home/gunshi/Downloads/SuiteSparse/SuiteSparse_config'
make[1]: Nothing to be done for`install'.
make[1]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/SuiteSparse_config'
( cd AMD && make install )
make[1]: Entering directory`/home/gunshi/Downloads/SuiteSparse/AMD'
( cd Lib  ; make install )
make[2]: Entering directory `/home/gunshi/Downloads/SuiteSparse/AMD/Lib'
make[2]: Nothing to be done for`install'.
make[2]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/AMD/Lib'
make[1]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/AMD'
( cd BTF && make install )
make[1]: Entering directory `/home/gunshi/Downloads/SuiteSparse/BTF'
( cd Lib ; make install )
make[2]: Entering directory`/home/gunshi/Downloads/SuiteSparse/BTF/Lib'
make[2]: Nothing to be done for `install'.
make[2]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/BTF/Lib'
make[1]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/BTF'
( cd CAMD && make install )
make[1]: Entering directory`/home/gunshi/Downloads/SuiteSparse/CAMD'
( cd Lib ; make install )
make[2]: Entering directory `/home/gunshi/Downloads/SuiteSparse/CAMD/Lib'
make[2]: Nothing to be done for`install'.
make[2]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/CAMD/Lib'
make[1]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/CAMD'
( cd CCOLAMD && make install )
make[1]: Entering directory `/home/gunshi/Downloads/SuiteSparse/CCOLAMD'
( cd Lib  ; make install )
make[2]: Entering directory`/home/gunshi/Downloads/SuiteSparse/CCOLAMD/Lib'
make[2]: Nothing to be done for `install'.
make[2]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/CCOLAMD/Lib'
make[1]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/CCOLAMD'
( cd COLAMD && make install )
make[1]: Entering directory`/home/gunshi/Downloads/SuiteSparse/COLAMD'
( cd Lib    ; make install )
make[2]: Entering directory `/home/gunshi/Downloads/SuiteSparse/COLAMD/Lib'
make[2]: Nothing to be done for`install'.
make[2]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/COLAMD/Lib'
make[1]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/COLAMD'
( cd CHOLMOD && make install )
make[1]: Entering directory `/home/gunshi/Downloads/SuiteSparse/CHOLMOD'
( cd Lib ; make install )
make[2]: Entering directory`/home/gunshi/Downloads/SuiteSparse/CHOLMOD/Lib'
cc -L/usr/local/lib -shared -Wl,-soname -Wl,libcholmod.so.3 -Wl,--no-undefined -fopenmp cholmod_aat.o cholmod_add.o cholmod_band.o cholmod_change_factor.o cholmod_common.o cholmod_complex.o cholmod_copy.o cholmod_dense.o cholmod_error.o cholmod_factor.o cholmod_memory.o cholmod_sparse.o cholmod_transpose.o cholmod_triplet.o cholmod_version.o cholmod_check.o cholmod_read.o cholmod_write.o cholmod_amd.o cholmod_analyze.o cholmod_colamd.o cholmod_etree.o cholmod_factorize.o cholmod_postorder.o cholmod_rcond.o cholmod_resymbol.o cholmod_rowcolcounts.o cholmod_rowfac.o cholmod_solve.o cholmod_spsolve.o cholmod_drop.o cholmod_horzcat.o cholmod_norm.o cholmod_scale.o cholmod_sdmult.o cholmod_ssmult.o cholmod_submatrix.o cholmod_vertcat.o cholmod_symmetry.o cholmod_rowadd.o cholmod_rowdel.o cholmod_updown.o cholmod_super_numeric.o cholmod_super_solve.o cholmod_super_symbolic.o cholmod_ccolamd.o cholmod_csymamd.o cholmod_metis.o cholmod_nesdis.o cholmod_camd.o cholmod_l_aat.o cholmod_l_add.o cholmod_l_band.o cholmod_l_change_factor.o cholmod_l_common.o cholmod_l_complex.o cholmod_l_copy.o cholmod_l_dense.o cholmod_l_error.o cholmod_l_factor.o cholmod_l_memory.o cholmod_l_sparse.o cholmod_l_transpose.o cholmod_l_triplet.o cholmod_l_version.o cholmod_l_check.o cholmod_l_read.o cholmod_l_write.o cholmod_l_amd.o cholmod_l_analyze.o cholmod_l_colamd.o cholmod_l_etree.o cholmod_l_factorize.o cholmod_l_postorder.o cholmod_l_rcond.o cholmod_l_resymbol.o cholmod_l_rowcolcounts.o cholmod_l_rowfac.o cholmod_l_solve.o cholmod_l_spsolve.o cholmod_l_drop.o cholmod_l_horzcat.o cholmod_l_norm.o cholmod_l_scale.o cholmod_l_sdmult.o cholmod_l_ssmult.o cholmod_l_submatrix.o cholmod_l_vertcat.o cholmod_l_symmetry.o cholmod_l_rowadd.o cholmod_l_rowdel.o cholmod_l_updown.o cholmod_l_super_numeric.o cholmod_l_super_solve.o cholmod_l_super_symbolic.o cholmod_l_ccolamd.o cholmod_l_csymamd.o cholmod_l_metis.o cholmod_l_nesdis.o cholmod_l_camd.o -o /usr/local/lib/libcholmod.so.3.0.11 -lm -lrt -Wl,-rpath=/usr/local/lib -lamd -lcolamd -lsuitesparseconfig -lccolamd -lcamd -lmetis -llapack -lopenblas
**/usr/bin/ld: cannot find -lmetis
collect2: error: ld returned 1 exit status
make[2]: **\* [/usr/local/lib/libcholmod.so.3.0.11] Error 1
make[2]: Leaving directory `/home/gunshi/Downloads/SuiteSparse/CHOLMOD/Lib'
make[1]: *** [install] Error 2
make[1]: Leaving directory`/home/gunshi/Downloads/SuiteSparse/CHOLMOD'
make: **\* [install] Error 2**

Any idea on how I can get it to install correctly?
Thanks.

**Comment by jluttine** [comment]
Sorry, I'm afraid I don't know. This repository just contains copies of the official releases (not the most recent ones, haven't had time to add those), I'm not involved in the project in any way. Perhaps you'll find some help from http://faculty.cse.tamu.edu/davis/suitesparse.html. I'll leave this open just in case someone else has the same issue or is able to help.

**Comment by carlosrojas** [comment]
You just need to install metis the link is provided in SuiteParse README.

> Some codes optionally use METIS 4.0.1
> (http://www-users.cs.umn.edu/~karypis/metis).  To use METIS, place a copy of
> the metis-4.0 directory in the same directory containing this README file.
> Be sure that you do not have a nested metis-4.0/metis-4.0 directory; SuiteSparse
> won't find METIS if you do this, which can happen with a zip file of metis-4.0
> on Windows.  The use of METIS will improve the ordering quality.

**Comment by CodeLenz** [comment]
I think the problem is in line 53 of Suitesparse_config.mk

ifeq (,$(findstring -DNPARTITION, $(CHOLMOD_CONFIG)))

that should be

ifeq (,$(findstring -DNPARTITION, $(CONFIG_PARTITION)))

Doing this modification, I could compile successfully.
