### ISSUE TITLE
Errors in compiling CHOLMOD

### ISSUE THREAD

**Issue by gokulhari** [jluttine/suitesparse#5]
Hi,
I tried compiling using make, with "make BLAS=-lopenblas". I get the following errors. I've tried on two Linux PCs running Ubuntu and the same happens in both. I'm using the most recent release version.

make[2]: Entering directory '/home/gokul/Downloads/suitesparse-5.3.0/CHOLMOD/Lib'
cc -L/home/gokul/Downloads/suitesparse-5.3.0/lib -shared -Wl,-soname -Wl,libcholmod.so.3 -Wl,--no-undefined -fopenmp cholmod_aat.o cholmod_add.o cholmod_band.o cholmod_change_factor.o cholmod_common.o cholmod_complex.o cholmod_copy.o cholmod_dense.o cholmod_error.o cholmod_factor.o cholmod_memory.o cholmod_sparse.o cholmod_transpose.o cholmod_triplet.o cholmod_version.o cholmod_check.o cholmod_read.o cholmod_write.o cholmod_amd.o cholmod_analyze.o cholmod_colamd.o cholmod_etree.o cholmod_factorize.o cholmod_postorder.o cholmod_rcond.o cholmod_resymbol.o cholmod_rowcolcounts.o cholmod_rowfac.o cholmod_solve.o cholmod_spsolve.o cholmod_drop.o cholmod_horzcat.o cholmod_norm.o cholmod_scale.o cholmod_sdmult.o cholmod_ssmult.o cholmod_submatrix.o cholmod_vertcat.o cholmod_symmetry.o cholmod_rowadd.o cholmod_rowdel.o cholmod_updown.o cholmod_super_numeric.o cholmod_super_solve.o cholmod_super_symbolic.o cholmod_ccolamd.o cholmod_csymamd.o cholmod_metis.o cholmod_nesdis.o cholmod_camd.o cholmod_l_aat.o cholmod_l_add.o cholmod_l_band.o cholmod_l_change_factor.o cholmod_l_common.o cholmod_l_complex.o cholmod_l_copy.o cholmod_l_dense.o cholmod_l_error.o cholmod_l_factor.o cholmod_l_memory.o cholmod_l_sparse.o cholmod_l_transpose.o cholmod_l_triplet.o cholmod_l_version.o cholmod_l_check.o cholmod_l_read.o cholmod_l_write.o cholmod_l_amd.o cholmod_l_analyze.o cholmod_l_colamd.o cholmod_l_etree.o cholmod_l_factorize.o cholmod_l_postorder.o cholmod_l_rcond.o cholmod_l_resymbol.o cholmod_l_rowcolcounts.o cholmod_l_rowfac.o cholmod_l_solve.o cholmod_l_spsolve.o cholmod_l_drop.o cholmod_l_horzcat.o cholmod_l_norm.o cholmod_l_scale.o cholmod_l_sdmult.o cholmod_l_ssmult.o cholmod_l_submatrix.o cholmod_l_vertcat.o cholmod_l_symmetry.o cholmod_l_rowadd.o cholmod_l_rowdel.o cholmod_l_updown.o cholmod_l_super_numeric.o cholmod_l_super_solve.o cholmod_l_super_symbolic.o cholmod_l_ccolamd.o cholmod_l_csymamd.o cholmod_l_metis.o cholmod_l_nesdis.o cholmod_l_camd.o -o /home/gokul/Downloads/suitesparse-5.3.0/lib/libcholmod.so.3.0.12 -lm -lrt -Wl,-rpath=/home/gokul/Downloads/suitesparse-5.3.0/lib -lamd -lcolamd -lsuitesparseconfig -lccolamd -lcamd -lmetis -llapack -lopenblas
//usr/local/lib/liblapack.a(xerbla.o): In function `xerbla_':
xerbla.f:(.text+0x53): undefined reference to `_gfortran_st_write'
xerbla.f:(.text+0x5e): undefined reference to `_gfortran_string_len_trim'
xerbla.f:(.text+0x73): undefined reference to `_gfortran_transfer_character_write'
xerbla.f:(.text+0x83): undefined reference to `_gfortran_transfer_integer_write'
xerbla.f:(.text+0x8b): undefined reference to `_gfortran_st_write_done'
xerbla.f:(.text+0x94): undefined reference to `_gfortran_stop_string'
/usr/bin/ld: //usr/local/lib/liblapack.a(dpotrf2.o): relocation R_X86_64_PC32 against symbol `dpotrf2_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:541: recipe for target '/home/gokul/Downloads/suitesparse-5.3.0/lib/libcholmod.so.3.0.12' failed
make[2]: *** [/home/gokul/Downloads/suitesparse-5.3.0/lib/libcholmod.so.3.0.12] Error 1
make[2]: Leaving directory '/home/gokul/Downloads/suitesparse-5.3.0/CHOLMOD/Lib'
Makefile:66: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/gokul/Downloads/suitesparse-5.3.0/CHOLMOD'
Makefile:40: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by jluttine** [comment]
This repository isn't the real home of SuiteSparse and I'm not involved in SuiteSparse in any way. I've just put the releases here for easier access. The home page of SuiteSparse is http://faculty.cse.tamu.edu/davis/suitesparse.html. So, it might be difficult to get support here. My guess: If you are compiling for OpenBLAS, you probably should set `LAPACK=""` because OpenBLAS already contains LAPACK functions. It also says `recompile with -fPIC`, so perhaps that should be done too.

**Comment by jluttine** [comment]
There is now an official GitHub repository. Please move the issue there if still valid. I'll archive this repository.

https://github.com/DrTimothyAldenDavis/SuiteSparse
